-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 11:10:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Walmart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Walmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Walmart` DEFAULT CHARACTER SET utf8 ;
USE `Walmart` ;

-- -----------------------------------------------------
-- Table `Walmart`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Vendas` (
  `vendasId` INT NOT NULL AUTO_INCREMENT,
  `vendasValor` VARCHAR(45) NULL,
  PRIMARY KEY (`vendasId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Funcionario` (
  `FuncionarioId` INT NOT NULL AUTO_INCREMENT,
  `FuncionarioNome` VARCHAR(45) NULL,
  `FuncionarioSalario` VARCHAR(45) NULL,
  `FuncionarioFuncao` VARCHAR(45) NULL,
  `Vendas_vendasId` INT NOT NULL,
  PRIMARY KEY (`FuncionarioId`, `Vendas_vendasId`),
  INDEX `fk_Funcionario_Vendas1_idx` (`Vendas_vendasId` ASC),
  CONSTRAINT `fk_Funcionario_Vendas1`
    FOREIGN KEY (`Vendas_vendasId`)
    REFERENCES `Walmart`.`Vendas` (`vendasId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Produto` (
  `ProdutoId` INT NOT NULL,
  `ProdutoNome` VARCHAR(45) NULL,
  `ProdutoPreco` VARCHAR(45) NULL,
  PRIMARY KEY (`ProdutoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Estoque` (
  `EstoqueId` INT NOT NULL,
  `EstoqueNome` VARCHAR(45) NULL,
  PRIMARY KEY (`EstoqueId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Fornecedor` (
  `FornecedorID` INT NOT NULL,
  `FornecedorNome` VARCHAR(45) NULL,
  `FornecedorTelefone` VARCHAR(45) NULL,
  PRIMARY KEY (`FornecedorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Produto_has_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Produto_has_Estoque` (
  `Produto_ProdutoId` INT NOT NULL,
  `Estoque_EstoqueId` INT NOT NULL,
  PRIMARY KEY (`Produto_ProdutoId`, `Estoque_EstoqueId`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_EstoqueId` ASC),
  INDEX `fk_Produto_has_Estoque_Produto_idx` (`Produto_ProdutoId` ASC),
  CONSTRAINT `fk_Produto_has_Estoque_Produto`
    FOREIGN KEY (`Produto_ProdutoId`)
    REFERENCES `Walmart`.`Produto` (`ProdutoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_EstoqueId`)
    REFERENCES `Walmart`.`Estoque` (`EstoqueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `UsuarioLogin` VARCHAR(45) NOT NULL,
  `UsuarioSenha` VARCHAR(45) NOT NULL,
  `Funcionario_FuncionarioId` INT NOT NULL,
  `Funcionario_Vendas_vendasId` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Funcionario1_idx` (`Funcionario_FuncionarioId` ASC, `Funcionario_Vendas_vendasId` ASC),
  CONSTRAINT `fk_Usuario_Funcionario1`
    FOREIGN KEY (`Funcionario_FuncionarioId` , `Funcionario_Vendas_vendasId`)
    REFERENCES `Walmart`.`Funcionario` (`FuncionarioId` , `Vendas_vendasId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Walmart`.`Vendas_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Walmart`.`Vendas_has_Produto` (
  `Vendas_vendasId` INT NOT NULL,
  `Produto_ProdutoId` INT NOT NULL,
  PRIMARY KEY (`Vendas_vendasId`, `Produto_ProdutoId`),
  INDEX `fk_Vendas_has_Produto_Produto1_idx` (`Produto_ProdutoId` ASC),
  INDEX `fk_Vendas_has_Produto_Vendas1_idx` (`Vendas_vendasId` ASC),
  CONSTRAINT `fk_Vendas_has_Produto_Vendas1`
    FOREIGN KEY (`Vendas_vendasId`)
    REFERENCES `Walmart`.`Vendas` (`vendasId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_has_Produto_Produto1`
    FOREIGN KEY (`Produto_ProdutoId`)
    REFERENCES `Walmart`.`Produto` (`ProdutoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
